source("R/models_and_tests/models_and_tests.R")

DEFAULT_MODELS <- list(
  ANOVA(),
  LOG_ANOVA(c = 0.001),
  LOG_ANOVA(c = 1),
  LOG_ANOVA(c = 10000),
  TWEEDIE_REGRESSION(xi = 1.2),
  TWEEDIE_REGRESSION(xi = "infer"),
  QUANTILE_REGRESSION(),
  QUANTILE_REGRESSION(tau = 0.75),
  WILCOXON_TEST(),
  PERMUTATION_TEST(),
  ZERO_INFLATED_GAMMA(),
  ZERO_INFLATED_LOGNORMAL(),
  force_computation(TWO_PART_T_TEST()),
  TWO_PART_WILCOXON_TEST(),
  ZERO_INFLATED_NORMAL(),
  ZERO_INFLATED_LOGNORMAL(sigma_per_group = TRUE),
  ZERO_INFLATED_GAMMA(sigma_per_group = TRUE),
  TWO_PART_T_TEST(use_welch = TRUE)
)

QR_MODELS <- list(
  QUANTILE_REGRESSION(tau = 0.1),
  QUANTILE_REGRESSION(tau = 0.25),
  QUANTILE_REGRESSION(),
  QUANTILE_REGRESSION(tau = 0.75),
  QUANTILE_REGRESSION(tau = 0.9),
  QUANTILE_REGRESSION(tau = 0.95)
)